stages:
  - build
  - test

build_project:
  stage: build
  script:
    - mkdir build
    - cd build
    - RISCV_TOOLCHAIN=/tank/work/dev/toolchains/riscv32i-tags-newlib-gcc/ cmake ../
    - make -j8
  artifacts:
    paths:
      - build/
    expire_in: 2h

test_project:
  stage: test
  script:
    - cd build/
    - ctest -LE nightly -j8
