stages:
  - build
  - test

build_project:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make
  artifacts:
    paths:
      - build/

test_project:
  stage: test
  script:
    - cd build/
    - ctest 
