stages:
  - build
  - test

build_project:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make
  artifacts:
    paths:
      - build/
    expire_in: 1 day

test_project:
  stage: test
  script:
    - cd build/
    - ctest -R "compliance_I-ADDI-01.S|compliance_I-BLTU-01.S|asm_sb|asm_csrrw_small|compliance_I-CSRRW-01.S|compliance_I-CSRRWI-01.S|compliance_I-CSRRS-01.S|compliance_I-CSRRSI-01.S"
